In [1]:
 #import sys
import copy
import time
import argparse
import numpy as np
#from tqdm import tqdm
#import itertools as its
import toolz.itertoolz as itz
#from matplotlib import pyplot as plt
from joblib import Parallel , delayed

In [2]:
lx = 2
ly = 4

In [3]:
def partition(a):    
    part = []
    for i in range(0,lx,2):
        for j in range(0,ly,2):
            part.append([a[i%lx,j%ly],a[i%lx,(j+1)%ly],a[(i+1)%lx,j%ly],a[(i+1)%lx,(j+1)%ly]])
    return np.asarray(part)

In [4]:
def combine(a):
    c = np.zeros((lx,ly))
    p = 0
    for k in range(int(lx/2)):
        for j in range(0,4,2):
            com = []
            [com.append([a[(i+k*int(ly/2))%lx,j],a[(i+k*int(ly/2))%lx,j+1]])  for i in range(0,int(ly/2))]
            c[p,:] = np.asarray(com).flatten()
            p+=1
    return c

In [5]:
def tetra_update(tetramer):
    if tetramer == [1,0,0,0]:
        return [[0,1,0,0],[0,0,1,0], [0,0,0,1]][np.random.randint(3)]
    elif tetramer == [0,1,0,0]:
        return [[1,0,0,0],[0,0,1,0], [0,0,0,1]][np.random.randint(3)]
    elif tetramer == [0,0,1,0]:
        return [[1,0,0,0],[0,1,0,0], [0,0,0,1]][np.random.randint(3)]
    elif tetramer == [0,0,0,1]:
        return [[1,0,0,0],[0,1,0,0], [0,0,1,0]][np.random.randint(3)]
    return(tetramer)

In [6]:
a = np.random.randint(2,size=(lx,ly))

In [7]:
a

array([[0, 0, 0, 0],
       [0, 0, 1, 0]])

In [8]:
bi_x, bi_y = np.random.randint(lx), np.random.randint(ly)
rolled = np.roll(np.roll(a,bi_x,axis=0),bi_y,axis=1)


In [9]:
rolled

array([[0, 0, 0, 0],
       [0, 0, 0, 1]])

In [10]:
np.roll(np.roll(rolled,-bi_y,axis=1),-bi_x,axis=0)

array([[0, 0, 0, 0],
       [0, 0, 1, 0]])

In [11]:
par_st = partition(np.roll(np.roll(a,bi_x,axis=0),bi_y,axis=1))

In [12]:
bi_x, bi_y

(0, 1)

In [13]:
par_st

array([[0, 0, 0, 0],
       [0, 0, 0, 1]])

In [14]:
comb = combine(par_st)

In [15]:
comb

array([[0., 0., 0., 0.],
       [0., 0., 0., 1.]])

In [16]:
np.roll(np.roll(comb,-bi_y,axis=1),-bi_x,axis=0)


array([[0., 0., 0., 0.],
       [0., 0., 1., 0.]])

In [17]:
a

array([[0, 0, 0, 0],
       [0, 0, 1, 0]])

In [19]:
np.roll(np.roll(combine(np.asarray(map(tetra_update,par_st))),-bi_y,axis=1),-bi_x,axis=0)

IndexError: too many indices for array: array is 0-dimensional, but 2 were indexed

In [22]:
list(map(tetra_update,par_st))

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [ ]:
np.roll(np.roll(list(map(tetra_update,par_st)),-bi_y,axis=1),-bi_x,axis=0)


In [ ]:
np.roll(np.roll(map(tetra_update,par_st),-bi_x,axis=0),-bi_y,axis=1)
